services:
  mongo1:
    image: mongo
    container_name: mongo1
    command: ["--replSet", "replica-set", "--bind_ip_all", "--port", "30001"]
    ports:
      - 30001:30001
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'replica-set',members:[{_id:0,host:\"mongo1:30001\"},{_id:1,host:\"mongo2:30002\"},{_id:2,host:\"mongo3:30003\"}]}).ok || rs.status().ok" | mongosh --port 30001 --quiet) -eq 1
      interval: 10s
      start_period: 30s

  mongo2:
    image: mongo
    container_name: mongo2
    command: ["--replSet", "replica-set", "--bind_ip_all", "--port", "30002"]
    ports:
      - 30002:30002

  mongo3:
    image: mongo
    container_name: mongo3
    command: ["--replSet", "replica-set", "--bind_ip_all", "--port", "30003"]
    ports:
      - 30003:30003
