# fly.toml app configuration file generated for bae-no-server on 2023-06-18T09:10:38+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bae-no-server"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
