name: Auto Assign

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened ]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Auto assign
        run: |
          logins=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}" \
            --jq '[.commits[].author.login] | unique')
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{\"assignees\":$logins"} \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
